[package]
name = "spip-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
native-tls = "0.2"
openssl = "0.10"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
uuid = "0.8"
libc = "0.2"
hex = "0.4"

