[package]
name = "spip-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
tokio = { version = "1", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hex = "0.4"
toml = "0.5"
